/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Level": "等级",
    "MAX": "最大",
    "Lab": "实验室",
    "Import Game": "导入",
    "Good Generator": "不错的生成器",
    "in this Prestige run.": "在这次声望赛中。",
    "Keep it in a safe place!": "把它放在安全的地方！",
    "Name": "名称",
    "Number Formatting": "数字格式",
    "Options": "选项",
    "Prestige": "声望",
    "Prestige Points": "声望点",
    "Prestige Points.": "声望点。",
    "Price": "价格",
    "Style": "样式",
    "The Lab": "实验室",
    "Export Game": "导出",
    "Cookies.": "饼干。",
    "Minimal": "最小",
    "Affects": "影响",
    "Automation": "自动化",
    "At": "在",
    "Buy": "购买",
    "BUY": "购买",
    "Buy All Upgrades": "购买全部升级",
    "Can you solve": "你能解决吗",
    "Cookies per Click.": "饼干每次点击。",
    "Cookies per Second.": "饼干每秒。",
    "Cookies so far.": "饼干到此为止。",
    "Generators": "生成器",
    "Max All Buildings": "最大所有建筑物",
    "Standard": "标准",
    "The Math Machine": "数学机器",
    "Upgrades": "升级",
    "Use This if the game runs slow": "如果游戏运行缓慢，请使用此选项",
    "You get": "你得到了",
    "You have 🕑 {{game.automatons}}": "你有 🕑 {{game.automatons}}",
    "You have clicked": "你点击了",
    "You have played for": "你玩了",
    "You made": "你制作了",
    "You prestiged": "你声望了",
    "You solved": "你解决了",
    "You spent": "你花费了",
    "Advanced Generator": "高级生成器",
    "Black Hole": "黑洞",
    "Good Job, you got 🍪{{NumberFormatter.format(mathMachine.lastReward, settings.numberFormatType)}}": "干得好，你得到了 🍪{{NumberFormatter.format(mathMachine.lastReward, settings.numberFormatType)}}",
    "Join my Discord Server": "加入我的 Discord 服务器",
    "Modern Generator": "现代生成器",
    "Ordinary Generator": "普通生成器",
    "Play further to reveal this Upgrade!": "进一步玩以揭示此升级！",
    "Play more Incremental Games": "玩更多增量游戏",
    "Prestige to get {{NumberFormatter.format(getPrestigePointsOnReset(cookies), settings.numberFormatType)}} Prestige Points": "声望获得 {{NumberFormatter.format(getPrestigePointsOnReset(cookies), settings.numberFormatType)}} 声望点",
    "Problems, translated to a boost of": "问题，转化为提升",
    "Respec all Upgrades": "重洗全部升级",
    "Respec Automators (Free": "重洗自动器 (免费",
    "Save Management": "存档管理",
    "Show bought Upgrades": "显示已购买升级",
    "Small Generator": "小型生成器",
    "Superb Generator": "一流生成器",
    "The Normal Cookie Clicker Style": "正常的 饼干点击器 样式",
    "This will reset all Progress made so far in return for powerful upgrades": "这将重置迄今为止取得的所有进度，以换取强大的升级",
    "times.": "次.",
    "Ultra Generator": "超级生成器",
    "Unreal Generator": "虚幻生成器",
    "Useless Generator": "无用的生成器",
    "You will get back all of your spent prestige points! Respec often to optimize your strategy.": "您将取回所有已用的声望点数！ 经常重新审视以优化您的策略。",
    "Generator Synergy": "生成器协同",
    "Click Bonus": "点击奖励",
    "CPS": "饼干每秒",
    "All Generators get a Boost based on total Generator levels": "所有生成器都获得基于生成器总等级的提升",
    "All Generators get a Boost based on Time Played": "所有生成器都会根据游戏时长获得提升",
    "All Generators get a Boost based on Total Clicks": "所有生成器都会根据总点击次数获得提升",
    "Get 🕑 1": "获得 🕑 1",
    "One for each person": "每人一份",
    "Time Bonus": "时间奖励",
    "You already got the hang of this.": "你已经掌握了这个窍门。",
    "You need {{NumberFormatter.format(1e33, settings.numberFormatType)}} Cookies to Prestige": "你需要 {{NumberFormatter.format(1e33, settings.numberFormatType)}} 饼干去声望",
    "Your first cookie! And it's really tasty.": "你的第一个饼干！ 而且真的很好吃。",
    "1 Million. That sure is a lot.": "1 Million。 那肯定很多。",
    "1 Trillion! You're rich! Time to do some research...": "1 Trillion！ 你很有钱！ 是时候做一些研究了...",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Ultra Generator Amplifier v": "超级生成器放大器 v",
    "Unreal Generator Amplifier v": "虚幻生成器放大器 v",
    "Useless Generator Amplifier v": "无用生成器放大器 v",
    "Small Generator Amplifier v": "小型生成器放大器 v",
    "Ordinary Generator Amplifier v": "一流生成器放大器 v",
    "Superb Generator Amplifier v": "普通生成器放大器 v",
    "Good Generator Amplifier v": "不错的生成器放大器 v",
    "Advanced Generator Amplifier v": "高级生成器放大器 v",
    "Modern Generator Amplifier v": "现代生成器放大器 v",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+)T$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+)B 🍪$/,
    /^🍪(.+)$/,
    /^(.+) ➡ (.+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) Hours, ([\d\.]+) Minutes, ([\d\.]+) Seconds$/, '$1小时，$2分钟，$3秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Base\-2 (.+)$/, '基础\-2 $1'],
    [/^Scientific (.+)$/, '科学 $1'],
    [/^Standard (.+)$/, '标准 $1'],
    [/^Letters (.+)$/, '字母 $1'],
    [/^Engineering (.+)$/, '工程符号 $1'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) \/ (.+) elves$/, '成本：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);